# Generated by Django 2.2.2 on 2020-07-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField(verbose_name='いいね')),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
    ]
