# Generated by Django 2.2.2 on 2020-07-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='diary',
            name='good',
            field=models.IntegerField(blank=True, null=True, verbose_name='いいね'),
        ),
    ]
