# Generated by Django 2.2.2 on 2020-07-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20200728_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField(blank=True, null=True, verbose_name='いいね')),
            ],
            options={
                'verbose_name_plural': 'Good',
            },
        ),
        migrations.RemoveField(
            model_name='diary',
            name='good',
        ),
    ]
