# Generated by Django 2.2.2 on 2020-07-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20200728_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='content',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='title',
        ),
        migrations.AddField(
            model_name='diary',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
        migrations.AddField(
            model_name='diary',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='距離'),
        ),
    ]
