# Generated by Django 2.2.2 on 2020-08-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20200808_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日付(例：2020-01-01)'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='距離(km)'),
        ),
    ]
