# Generated by Django 2.2.2 on 2020-08-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20200809_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField(blank=True, null=True, verbose_name='いいね')),
            ],
            options={
                'verbose_name_plural': 'Good',
            },
        ),
    ]
