# Generated by Django 2.2.2 on 2020-07-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='good',
            field=models.IntegerField(blank=True, null=True, verbose_name='いいね'),
        ),
    ]
