# Generated by Django 2.2.2 on 2020-07-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='good',
        ),
    ]
